spring:
  application:
    name: bcb-core-app
  datasource:
    url: jdbc:postgresql://bcb-postgres-db:5432/bcb_db
    username: postgres
    password: bcbtest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl.auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
bcb:
  sms-simulator:
    uri: "http://bcb-sms-simulator:8081"

